#!/bin/bash



find . -iname \*.[h] -exec grep --color -wn -H $1 \{\} \;

#find . -iname \*.lua -exec grep --color -wn -H $1 \{\} \;

#find . -iname \*.xml -exec grep --color -wn -H $1 \{\} \;

